### ISSUE TITLE
Demo colab gives an error

### ISSUE THREAD

**Issue by abdcef** [pszemraj/vid2cleantxt#16]
I get this error when running th edemo notebook:

`
data folder is set to `/usr/local/lib/python3.7/dist-packages/neuspell/../data` script
timeout                                   Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py](https://localhost:8080/#) in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    425                     # Otherwise it looks like a bug in the code.
--> 426                     six.raise_from(e, None)
    427         except (SocketTimeout, BaseSSLError, SocketError) as e:

32 frames
timeout: The read operation timed out

During handling of the above exception, another exception occurred:

ReadTimeoutError                          Traceback (most recent call last)
ReadTimeoutError: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10.0)

During handling of the above exception, another exception occurred:

ReadTimeout                               Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/requests/adapters.py](https://localhost:8080/#) in send(self, request, stream, timeout, verify, cert, proxies)
    527                 raise SSLError(e, request=request)
    528             elif isinstance(e, ReadTimeoutError):
--> 529                 raise ReadTimeout(e, request=request)
    530             else:
    531                 raise

ReadTimeout: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10.0)
`

**Comment by pszemraj** [comment]
Hello there!

I'm sorry that you're experiencing issues with the demo notebook and the delay in response - for some reason, I didn't get/see a notification for this one. It looks like you're getting a `ReadTimeoutError,` which suggests a problem with the connection to the server. This could be due to a temporary internet error, or it could be due to a problem with the server itself.

Have you tried again recently and gotten the same issue?

**Comment by pszemraj** [comment]
Hey, going to close this out as it's been a month - feel free to reopen if you have issues still!
