### ISSUE TITLE
[Doubt] Can you kindly explain what chunk_length dictates? 

### ISSUE THREAD

**Issue by PyroShade** [pszemraj/vid2cleantxt#20]
How good or bad the output is with change of this attribute? What is the unit (frames, seconds)? 
In the default setting of chunk_length=30, I can find a lot of text missing.

**Comment by pszemraj** [comment]
hi! the unit is seconds. there should be some warnings printed out in this case - could you give some more specific examples?

btw - I've noticed that this issue can be specific to an audio/video instance and a particular Whisper model. without knowing more info, I'd recommend trying a different one and seeing if the same issue occurs.

**Comment by pszemraj** [comment]
Hi, just wanted to check in on this. Any luck with other model sizes/any other questions? Otherwise, I'll close this for now.
